# Generated by Django 5.2.7 on 2025-11-03 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('estimated_cost', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day Plan',
                'verbose_name_plural': 'Day Plans',
                'db_table': 'day_plans',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=100, unique=True)),
                ('is_public_link', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Itinerary Share',
                'verbose_name_plural': 'Itinerary Shares',
                'db_table': 'itinerary_shares',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('car', 'Car/Taxi'), ('bike', 'Bike/Scooter'), ('auto', 'Auto-rickshaw'), ('metro', 'Metro'), ('ferry', 'Ferry'), ('walk', 'Walking'), ('other', 'Other')], max_length=20)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('seat_number', models.CharField(blank=True, max_length=50)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('cost', models.FloatField()),
                ('booking_status', models.CharField(default='planned', max_length=20)),
                ('carbon_footprint_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transportation',
                'verbose_name_plural': 'Transportations',
                'db_table': 'transportations',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('attraction', 'Attraction Visit'), ('meal', 'Meal'), ('transport', 'Transportation'), ('accommodation', 'Accommodation'), ('free_time', 'Free Time'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('estimated_cost', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.accommodation')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.attraction')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.restaurant')),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary.dayplan')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('number_of_travelers', models.IntegerField(default=1)),
                ('companion_type', models.CharField(blank=True, max_length=50)),
                ('total_budget', models.FloatField()),
                ('budget_per_person', models.FloatField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pace', models.CharField(default='moderate', max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
                'db_table': 'itineraries',
                'ordering': ['-created_at'],
            },
        ),
    ]
