# Generated by Django 5.2.7 on 2025-11-03 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='itinerary.itinerary'),
        ),
        migrations.AddField(
            model_name='itineraryshare',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='itinerary.itinerary'),
        ),
        migrations.AddField(
            model_name='itineraryshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itineraryshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportation',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='itinerary.itinerary'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['user', 'status'], name='itineraries_user_id_444591_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['destination'], name='itineraries_destina_349533_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('itinerary', 'day_number')},
        ),
    ]
