# Generated by Django 5.2.7 on 2025-11-04 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_intent', models.CharField(max_length=100)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('reply_text', models.CharField(max_length=100)),
                ('reply_value', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Reply',
                'verbose_name_plural': 'Quick Replies',
                'db_table': 'quick_replies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('session_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_context', models.JSONField(blank=True, default=dict)),
                ('extracted_info', models.JSONField(blank=True, default=dict)),
                ('total_messages', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_flow', models.CharField(blank=True, max_length=100)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('travel_dates', models.JSONField(blank=True, default=dict)),
                ('budget', models.JSONField(blank=True, default=dict)),
                ('companions', models.JSONField(blank=True, default=dict)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('last_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_info', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Stores conversation history and context')),
                ('pending_questions', models.JSONField(blank=True, default=list)),
                ('answered_questions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Conversation State',
                'verbose_name_plural': 'Conversation States',
                'db_table': 'conversation_states',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=100)),
                ('detected_entities', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('translated_content', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chat_sessio_user_id_d84cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'timestamp'], name='messages_session_f940d1_idx'),
        ),
    ]
