# Generated by Django 5.2.7 on 2025-11-03 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField()),
                ('geography_types', models.JSONField(blank=True, default=list)),
                ('experience_types', models.JSONField(blank=True, default=list)),
                ('landscape_types', models.JSONField(blank=True, default=list)),
                ('spiritual_focus', models.JSONField(blank=True, default=list)),
                ('budget_range_min', models.IntegerField(help_text='Minimum budget in INR')),
                ('budget_range_max', models.IntegerField(help_text='Maximum budget in INR')),
                ('typical_duration', models.IntegerField(help_text='Typical trip duration in days')),
                ('best_time_to_visit', models.JSONField(blank=True, default=list)),
                ('avoid_months', models.JSONField(blank=True, default=list)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=20)),
                ('safety_rating', models.FloatField(default=0.0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField(help_text='Altitude in meters')),
                ('climate_type', models.CharField(choices=[('Tropical', 'Tropical'), ('Subtropical', 'Subtropical'), ('Temperate', 'Temperate'), ('Alpine', 'Alpine'), ('Arid', 'Arid')], max_length=50)),
                ('average_temperature_range', models.CharField(max_length=50)),
                ('nearest_airport', models.CharField(max_length=255)),
                ('nearest_railway_station', models.CharField(max_length=255)),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'db_table': 'destinations',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='destination_name_b9b5c8_idx'), models.Index(fields=['state', 'country'], name='destination_state_485661_idx'), models.Index(fields=['popularity_score'], name='destination_popular_04b6f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Beach', 'Beach'), ('Historical', 'Historical'), ('Spiritual/Historical', 'Spiritual/Historical'), ('Spiritual', 'Spiritual'), ('Natural', 'Natural'), ('Adventure', 'Adventure'), ('Cultural', 'Cultural'), ('Wildlife', 'Wildlife'), ('Museum', 'Museum'), ('Monument', 'Monument'), ('Park', 'Park'), ('Temple', 'Temple'), ('Fort', 'Fort'), ('Lake', 'Lake'), ('Waterfall', 'Waterfall'), ('ViewPoint', 'View Point')], max_length=50)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_attractions', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
                'db_table': 'attractions',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Luxury Resort', 'Luxury Resort'), ('Boutique/Luxury', 'Boutique/Luxury'), ('Hotel', 'Hotel'), ('Budget Hotel', 'Budget Hotel'), ('Homestay', 'Homestay'), ('Guest House', 'Guest House'), ('Hostel', 'Hostel'), ('Villa', 'Villa'), ('Cottage', 'Cottage'), ('Camp', 'Camp'), ('Lodge', 'Lodge')], max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_accommodations', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'db_table': 'accommodations',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_category', models.CharField(max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='destinations.destination')),
            ],
            options={
                'db_table': 'destination_tags',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_restaurants', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurants',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDestinationInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('saved', 'Saved'), ('shared', 'Shared'), ('booked', 'Booked'), ('reviewed', 'Reviewed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
            ],
            options={
                'db_table': 'user_destination_interactions',
            },
        ),
    ]
