# Generated by Django 5.2.7 on 2025-11-03 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdestinationinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['destination', 'type'], name='attractions_destina_3b17da_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['rating'], name='attractions_rating_81539c_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['destination', 'type'], name='accommodati_destina_3e5404_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['rating'], name='accommodati_rating_fd7c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationtag',
            index=models.Index(fields=['tag_name'], name='destination_tag_nam_23aca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='destinationtag',
            unique_together={('destination', 'tag_name')},
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['destination', 'cuisine'], name='restaurants_destina_ad259f_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['rating'], name='restaurants_rating_93f534_idx'),
        ),
        migrations.AddIndex(
            model_name='userdestinationinteraction',
            index=models.Index(fields=['user', 'timestamp'], name='user_destin_user_id_151295_idx'),
        ),
        migrations.AddIndex(
            model_name='userdestinationinteraction',
            index=models.Index(fields=['destination', 'interaction_type'], name='user_destin_destina_aed04e_idx'),
        ),
    ]
